### ISSUE TITLE
Issue with ROM

### ISSUE THREAD

**Issue by NoizeBombHD** [ShadySheikah/IfPatcher#1]
So I just downloaded the patcher, and it at first started to work as intended. However, it then told me of a missing part of the patcher, which was the rom, and gave me an error prompt with it stating that it is missing a part, that part being the rom of the patcher

**Comment by ShadySheikah** [comment]
In order to use the patcher, you will need to also download a zip of the fan translation's repository (found [here](https://github.com/TeamIf/FireEmblemIf-FanTranslation)) and extract the contents to a reachable location on your computer.

The fan translation's files are separated into three folders: `exe`, `rom`, and `dlc`. The folder containing those three folders is what the patcher looks for when beginning the patching process, and it's what you'll want to use for the `Patch Folder` area of the program. If you provide a location that doesn't contain an `exe` or `rom` folder, the program will throw an error.
